const appname = "Shimla Enterprises";
const appversion = "Version 1.0.0";
const credits = "@Shyam Devs";
const email = "Email";
const emailHint = "sample@gmail.com";
const password = "Password";
const passwordHint = "*******";
const retypePassWord = "Conform Password";
const name = "Name";
const nameHint = "Enter Your Name";
const forgetPass = "Forget Password";
const login = " Log in ";
const signup = "Sign Up";
const creatNewAccount = "or, create a new account";
const loginWith = "Log in with";
const privacyPolicy = " Privacy Policy ";
const termAndCond = " Terms and Condition ";
const alredyHaveAccount = "Already have an account?";
// home Strings
const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";
//home Screen Strings
const searchanything = "Search anything...",
    todayDeal = "Today's Deal",
    flashsale = "Flash Sale",
    topSellers = "Top Sellers",
    brand = "Brand",
    topCategories = "Top Categories",
    womenDress = "Women Derss",
    girlsWatches = "Girls Watches",
    mobilePhone = "Mobile Phone",
    boyGlasses = "Boy Glasses",
    tShirts = "TShirts",
    girlsDress = "Girls Dreses",
    featuredProduct = "Featured Products",
    featuredCategories = "Featured Categories";
// categary strings
const womenClothing = "Women Clothing",
    menClothingFashion = "Men Clothing & Fashion",
    compAccess = "Computer & Accessories",
    automobile = "Automobile",
    kidstoys = "kids & Toys",
    sports = "Sports",
    jewelery = "Jewelery",
    cellphone = "Cellphone & Tab",
    furniture = "Furniture";
// item deatails string
const video = "video",
    reviews = "Reviews",
    sellerpolicy = "Seller Policy",
    returnpolity = "Return Policy",
    supportPolicy = "Support Policy",
    productsyoumaylike = "Products you may also like";
